# Topic Modelling

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
TTF = pd.read_csv("https://raw.githubusercontent.com/Aldi-880/dataset-ppw/main/datavcm2.csv")
TTF

Abstrak  00  000  00001  0001  \
0    sistem informasi akademik ( siakad ) sistem in...   0    0      0     0   
1    berjalannya koneksi jaringan komputer lancar g...   0    0      0     0   
2    web server perangkat lunak server berfungsi me...   0    0      0     0   
3    penjadwalan kuliah perguruan kompleks . permas...   0    0      0     0   
4    seiring perkembangan teknologi didunia , muncu...   0    0      0     0   
..                                                 ...  ..  ...    ...   ...   
850  toko tas deeolshop menjual tas model kekinian ...   0    0      0     0   
851  sepak bola salah olahraga digemari remaja bela...   0    0      0     0   
852  perguruan salah jenjang pendidikan sekolah men...   0    0      0     0   
853  investasi saham memiliki resiko kerugian perge...   0    0      0     0   
854  information retrieval ( ir ) pengambilan infor...   0    0      0     0   

     000505341  000506436  000792353  00086  00089  ...  zara  zat  zcz  zf  \
0            0          0          0      0      0  ...     0    0    0   0   
1            0          0          0      0      0  ...     0    0    0   0   
2            0          0          0      0      0  ...     0    0    0   0   
3            0          0          0      0      0  ...     0    0    0   0   
4            0          0          0      0      0  ...     0    0    0   0   
..         ...        ...        ...    ...    ...  ...   ...  ...  ...  ..   
850          0          0          0      0      0  ...     1    0    0   0   
851          0          0          0      0      0  ...     0    0    0   0   
852          0          0          0      0      0  ...     0    0    0   0   
853          0          0          0      0      0  ...     0    0    0   0   
854          0          0          0      0      0  ...     0    0    0   0   

     zona  zone  zoning  zoom  zucara  zungu  
0       0     0       0     0       0      0  
1       0     0       0     0       0      0  
2       0     0       0     0       0      0  
3       0     0       0     0       0      0  
4       0     0       0     0       0      0  
..    ...   ...     ...   ...     ...    ...  
850     0     0       0     0       0      0  
851     0     0       0     0       0      0  
852     0     0       0     0       0      0  
853     0     0       0     0       0      0  
854     0     0       0     0       0      0  

[855 rows x 8878 columns]

In [ ]:
TF = pd.read_csv("https://raw.githubusercontent.com/Aldi-880/dataset-ppw/main/datavcm2.csv")
TF

Abstrak  00  000  00001  0001  \
0    sistem informasi akademik ( siakad ) sistem in...   0    0      0     0   
1    berjalannya koneksi jaringan komputer lancar g...   0    0      0     0   
2    web server perangkat lunak server berfungsi me...   0    0      0     0   
3    penjadwalan kuliah perguruan kompleks . permas...   0    0      0     0   
4    seiring perkembangan teknologi didunia , muncu...   0    0      0     0   
..                                                 ...  ..  ...    ...   ...   
850  toko tas deeolshop menjual tas model kekinian ...   0    0      0     0   
851  sepak bola salah olahraga digemari remaja bela...   0    0      0     0   
852  perguruan salah jenjang pendidikan sekolah men...   0    0      0     0   
853  investasi saham memiliki resiko kerugian perge...   0    0      0     0   
854  information retrieval ( ir ) pengambilan infor...   0    0      0     0   

     000505341  000506436  000792353  00086  00089  ...  zara  zat  zcz  zf  \
0            0          0          0      0      0  ...     0    0    0   0   
1            0          0          0      0      0  ...     0    0    0   0   
2            0          0          0      0      0  ...     0    0    0   0   
3            0          0          0      0      0  ...     0    0    0   0   
4            0          0          0      0      0  ...     0    0    0   0   
..         ...        ...        ...    ...    ...  ...   ...  ...  ...  ..   
850          0          0          0      0      0  ...     1    0    0   0   
851          0          0          0      0      0  ...     0    0    0   0   
852          0          0          0      0      0  ...     0    0    0   0   
853          0          0          0      0      0  ...     0    0    0   0   
854          0          0          0      0      0  ...     0    0    0   0   

     zona  zone  zoning  zoom  zucara  zungu  
0       0     0       0     0       0      0  
1       0     0       0     0       0      0  
2       0     0       0     0       0      0  
3       0     0       0     0       0      0  
4       0     0       0     0       0      0  
..    ...   ...     ...   ...     ...    ...  
850     0     0       0     0       0      0  
851     0     0       0     0       0      0  
852     0     0       0     0       0      0  
853     0     0       0     0       0      0  
854     0     0       0     0       0      0  

[855 rows x 8878 columns]

In [ ]:
#jumlah topik, parameter topik dalam satu dokumen, parameter dalam setiap kata ke dalam satu topik, parameter nilai acak, terasi dalam lda
lda = LatentDirichletAllocation(n_components=6, doc_topic_prior=0.2, topic_word_prior=0.1,random_state=42,max_iter=1)
lda_top=lda.fit_transform(TF)

ValueError: ignored

In [ ]:
judul = TTF["Judul"]

KeyError: ignored

In [ ]:
print(lda_top.shape)  # (no_of_doc,no_of_topics)
print(lda_top)

(913, 6)
[[2.03723787e-03 8.31468379e-01 2.03203910e-03 2.02417350e-03
  2.03018241e-03 1.60407988e-01]
 [9.92610737e-01 1.47521535e-03 1.47280701e-03 1.48758909e-03
  1.47831438e-03 1.47533741e-03]
 [1.96152539e-03 1.96987630e-03 1.26687770e-01 1.95832418e-03
  2.44114074e-01 6.23308430e-01]
 ...
 [1.04315353e-01 9.75769870e-04 9.67616817e-04 8.91797942e-01
  9.74127225e-04 9.69191587e-04]
 [2.19489761e-03 9.89039394e-01 2.17645030e-03 2.19895241e-03
  2.21124968e-03 2.17905619e-03]
 [1.98376785e-01 1.70366010e-03 7.94808393e-01 1.71259487e-03
  1.70419639e-03 1.69437053e-03]]


In [ ]:
#bobot setiap topik terhadap dokumen
U = pd.DataFrame(lda_top, columns=['Topik 1','Topik 2','Topik 3','Topik 4','Topik 5','Topik 6'])
U["Judul"] = judul
U

Topik 1   Topik 2   Topik 3   Topik 4   Topik 5   Topik 6  \
0    0.002037  0.831468  0.002032  0.002024  0.002030  0.160408   
1    0.992611  0.001475  0.001473  0.001488  0.001478  0.001475   
2    0.001962  0.001970  0.126688  0.001958  0.244114  0.623308   
3    0.002254  0.002248  0.002256  0.988723  0.002265  0.002255   
4    0.002622  0.002632  0.002621  0.002611  0.986891  0.002623   
..        ...       ...       ...       ...       ...       ...   
908  0.001500  0.001508  0.992473  0.001497  0.001508  0.001514   
909  0.001842  0.001857  0.371237  0.001850  0.001865  0.621350   
910  0.104315  0.000976  0.000968  0.891798  0.000974  0.000969   
911  0.002195  0.989039  0.002176  0.002199  0.002211  0.002179   
912  0.198377  0.001704  0.794808  0.001713  0.001704  0.001694   

                                                 Judul  
0    Pengaruh Penggunaan Media Audio Visual Terhada...  
1    Strategi Sekolah dalam Upaya Penguatan Karakte...  
2    Perbandingan Hasil Belajar Cooperative Learnin...  
3    Kemampuan Berpikir Tingkat Tinggi Siswa Kelas ...  
4    Hubungan Antara Kemandirian Belajar dengan Has...  
..                                                 ...  
908  PENGEMBANGAN MAJALAH BERBASIS GAME MOBILE LEGE...  
909  PENGEMBANGAN PERANGKAT PEMBELAJARAN MODEL\nPRO...  
910  Problematika Pembelajaran Daring Siswa Kelas R...  
911  PENDAMPINGAN ORANG TUA DALAM PROSES BELAJAR AN...  
912  peran Guru Dalam Menanamkan NIlai-Nilai Kearif...  

[913 rows x 7 columns]

In [ ]:
print(lda.components_)
print(lda.components_.shape)  # (no_of_topics*no_of_words)

[[1.74965067 0.10016838 0.30439954 ... 2.0995227  0.50261065 0.10002677]
 [0.10008741 0.10017835 0.10004379 ... 0.10008527 0.10004793 0.10002111]
 [0.10007482 0.72748317 0.10004262 ... 0.10010243 0.10071593 1.09987745]
 [0.10008324 2.0743115  0.68261422 ... 0.10009469 0.10005535 0.10002302]
 [0.10007374 0.10016419 0.31284154 ... 0.10010392 0.23112056 0.10002223]
 [0.45003012 0.49769442 0.10005829 ... 0.10009099 0.56544958 0.10002941]]
(6, 4394)


In [ ]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,(lda.components_.shape[1]+1)):
  masukan = TF.columns[i-1]
  label.append(masukan)
VT_tabel = pd.DataFrame(lda.components_,columns=label)
VT_tabel.rename(index={0:"Topik 1",1:"Topik 2",2:"Topik 3",3:"Topik 4",4:"Topik 5",5:"Topik 6"}).transpose()

Topik 1   Topik 2   Topik 3   Topik 4   Topik 5   Topik 6
ab      1.749651  0.100087  0.100075  0.100083  0.100074  0.450030
abad    0.100168  0.100178  0.727483  2.074311  0.100164  0.497694
abai    0.304400  0.100044  0.100043  0.682614  0.312842  0.100058
abar    0.100179  0.100194  0.100214  0.100182  0.730733  5.468498
abd     0.100057  0.171600  0.213376  0.100039  0.852327  0.162601
...          ...       ...       ...       ...       ...       ...
zholam  0.130634  0.100039  0.100034  0.100049  0.410653  0.758591
zn      0.100089  0.781593  0.100078  0.100077  0.418054  0.100110
zr      2.099523  0.100085  0.100102  0.100095  0.100104  0.100091
ztabel  0.502611  0.100048  0.100716  0.100055  0.231121  0.565450
zulfa   0.100027  0.100021  1.099877  0.100023  0.100022  0.100029

[4394 rows x 6 columns]

In [ ]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(lda_top)
cluster_labels = kmeans.labels_
data = {'Dokumen': range(len(cluster_labels)), 'Cluster': cluster_labels}
duf = pd.DataFrame(data)
#  df
CL = duf["Cluster"]
CL

0      1
1      1
2      1
3      1
4      1
      ..
908    0
909    1
910    1
911    1
912    0
Name: Cluster, Length: 913, dtype: int32

In [ ]:
#bobot setiap topik terhadap dokumen
U["Clustering"] = cluster_labels
U

Topik 1   Topik 2   Topik 3   Topik 4   Topik 5   Topik 6  \
0    0.002037  0.831468  0.002032  0.002024  0.002030  0.160408   
1    0.992611  0.001475  0.001473  0.001488  0.001478  0.001475   
2    0.001962  0.001970  0.126688  0.001958  0.244114  0.623308   
3    0.002254  0.002248  0.002256  0.988723  0.002265  0.002255   
4    0.002622  0.002632  0.002621  0.002611  0.986891  0.002623   
..        ...       ...       ...       ...       ...       ...   
908  0.001500  0.001508  0.992473  0.001497  0.001508  0.001514   
909  0.001842  0.001857  0.371237  0.001850  0.001865  0.621350   
910  0.104315  0.000976  0.000968  0.891798  0.000974  0.000969   
911  0.002195  0.989039  0.002176  0.002199  0.002211  0.002179   
912  0.198377  0.001704  0.794808  0.001713  0.001704  0.001694   

                                                 Judul  Clustering  
0    Pengaruh Penggunaan Media Audio Visual Terhada...           1  
1    Strategi Sekolah dalam Upaya Penguatan Karakte...           1  
2    Perbandingan Hasil Belajar Cooperative Learnin...           1  
3    Kemampuan Berpikir Tingkat Tinggi Siswa Kelas ...           1  
4    Hubungan Antara Kemandirian Belajar dengan Has...           1  
..                                                 ...         ...  
908  PENGEMBANGAN MAJALAH BERBASIS GAME MOBILE LEGE...           0  
909  PENGEMBANGAN PERANGKAT PEMBELAJARAN MODEL\nPRO...           1  
910  Problematika Pembelajaran Daring Siswa Kelas R...           1  
911  PENDAMPINGAN ORANG TUA DALAM PROSES BELAJAR AN...           1  
912  peran Guru Dalam Menanamkan NIlai-Nilai Kearif...           0  

[913 rows x 8 columns]

In [ ]:
clus0 = U[U['Clustering'] == 0][['Judul', 'Clustering']]
clus0

Judul  Clustering
8    PERBANDINGAN HASIL BELAJAR IPA DENGAN MODEL QU...           0
14   KOMPARASI PRESTASI BELAJAR SISWA ANTARA MODEL ...           0
17   PENGARUH MODEL QUANTUM TEACHING TEKNIK TANDUR ...           0
20   PENGARUH PEMBELAJARAN BERBASIS NILAI DENGAN ME...           0
21   PERBANDINGAN MODEL PEMBELAJARAN KOOPERATIF TIP...           0
..                                                 ...         ...
900  PENGEMBANGAN MEDIA GAMBAR BERSERI BERBASIS KEA...           0
903  PENGEMBANGAN PERANGKAT PEMBELAJARAN MATEMATIKA...           0
905  PENGEMBANGAN MEDIA PEMBELAJARAN PETI “PETA I...           0
908  PENGEMBANGAN MAJALAH BERBASIS GAME MOBILE LEGE...           0
912  peran Guru Dalam Menanamkan NIlai-Nilai Kearif...           0

[236 rows x 2 columns]

In [ ]:
clus1 = U[U['Clustering'] == 1][['Judul', 'Clustering']]
clus1

Judul  Clustering
0    Pengaruh Penggunaan Media Audio Visual Terhada...           1
1    Strategi Sekolah dalam Upaya Penguatan Karakte...           1
2    Perbandingan Hasil Belajar Cooperative Learnin...           1
3    Kemampuan Berpikir Tingkat Tinggi Siswa Kelas ...           1
4    Hubungan Antara Kemandirian Belajar dengan Has...           1
..                                                 ...         ...
906  ANALISIS FAKTOR-FAKTOR YANG MEMPENGARUHI HASIL...           1
907  PENANGANAN SISWA DISLEKSIA DENGAN METODE FERNA...           1
909  PENGEMBANGAN PERANGKAT PEMBELAJARAN MODEL\nPRO...           1
910  Problematika Pembelajaran Daring Siswa Kelas R...           1
911  PENDAMPINGAN ORANG TUA DALAM PROSES BELAJAR AN...           1

[677 rows x 2 columns]